name: Publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Set latest version
      run: |
        export VERSION=`curl https://marketplace.visualstudio.com/items?itemName=bot-man.workspace | grep '"Version":' | sed 's/^.*"Version":"\([^"]*\)".*$/\1/g'`
        echo Set current version to "$VERSION"
        sed -i 's/"version": "[^"]*"/"version": "'"$VERSION"'"/g' package.json
    - name: Publish a new version
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        rm -r .git
        npm install
        npm install -g vsce
        vsce publish patch -p $TOKEN
