name: Publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install vsce
      run: |
        npm install -g vsce
    - name: Package and Publish
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        npm install
        vsce publish -p $TOKEN
